import { useState } from "react";
import type { Contact } from "./types";
import { contactFromCalendar, scanCalendarMeetups, type CalendarMonth } from "./calendar";
import "./whatsapp-import.css";

type Props = { initialName?: string; initialEmail?: string; onClose: () => void; onImported: (contact: Contact) => void; embedded?: boolean };

export default function CalendarImport({ initialName, initialEmail, onClose, onImported, embedded = false }: Props) {
  const [name, setName] = useState(initialName ?? ""); const [email, setEmail] = useState(initialEmail ?? ""); const [includeTitles, setIncludeTitles] = useState(false); const [months, setMonths] = useState<CalendarMonth[] | null>(null); const [matches, setMatches] = useState(0); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const scan = async () => { if (!name.trim()) return; setError(null); setLoading(true); try { const result = await scanCalendarMeetups(name.trim(), email, includeTitles); if (!result.match_count) { setError("No matching calendar events were found in the last 12 months."); return; } if (result.months.filter((month) => month.meetup_count > 0).length < 2) { setError("There is not enough calendar history for a useful pattern yet. Try again after more than one month of events."); return; } setMonths(result.months); setMatches(result.match_count); } catch (reason) { setError(reason instanceof Error ? reason.message : "Calendar access was not available. Check the permission and try again."); } finally { setLoading(false); } };
  const confirm = () => { if (months && name.trim()) onImported(contactFromCalendar(name.trim(), email, months)); };
  const content = <section className="whatsapp-import calendar-import" aria-label="Add from calendar" onClick={(event) => event.stopPropagation()}><button className="form-close" type="button" aria-label={embedded ? "Back to data sources" : "Close"} onClick={onClose}>{embedded ? "‹" : "×"}</button>{months ? <><header><p>Calendar meetups</p><h3>Check the monthly count</h3><span>{matches} matching calendar events. In Touch keeps only these monthly counts for this session.</span></header><div className="monthly-preview" aria-label="Derived monthly meetup counts">{months.map((month) => <div key={month.label}><span>{month.label}</span><strong>{month.meetup_count}</strong><small>calendar meetups</small></div>)}</div><p className="privacy-statement">Processed entirely on your device. Event titles, notes, places, and guest lists are never stored or transmitted.</p><button className="submit-person" type="button" onClick={confirm}>Add {name.trim()} to tracking</button></> : <><header><p>Calendar meetups</p><h3>Find time you shared</h3><span>In Touch looks through the past 12 months of this phone’s synced calendar.</span></header><p className="privacy-statement">Processed entirely on your device. Event details are used only to find this person, then discarded; no calendar content is stored or transmitted.</p><label className="import-name">Display name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Their name in In Touch" autoFocus/></label><label className="import-name">Email address <small>Recommended for accurate attendee matching</small><input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" type="email"/></label><label className="title-match"><input type="checkbox" checked={includeTitles} onChange={(event) => setIncludeTitles(event.target.checked)}/><span>Also match their name in event titles</span><small>Optional — review the count before adding.</small></label><button className="submit-person" type="button" disabled={!name.trim() || loading} onClick={() => void scan()}>{loading ? "Checking calendar…" : "Find calendar meetups"}</button>{error && <p className="import-error" role="alert">{error}</p>}<p className="import-help">Invitees are the most reliable match. Calendar events are a record of scheduled time, not proof that a meeting happened.</p></>}</section>;
  return embedded ? content : <div className="modal-backdrop whatsapp-backdrop" onClick={onClose}>{content}</div>;
}
