import { animate, motion, useMotionValue, useReducedMotion } from "framer-motion";
import { useEffect, useState } from "react";
import type { Contact } from "./types";
import { deltaFor, rowFor, signalField, type SignalKey } from "./utils";

const signals: { key: SignalKey; label: string; icon: string; unit: string }[] = [{ key: "texts", label: "Texts", icon: "◌", unit: "/wk" }, { key: "calls", label: "Calls", icon: "⌁", unit: "/mo" }, { key: "meetups", label: "Meetups", icon: "○", unit: "/mo" }];
function Count({ value }: { value: number }) { const reduced = useReducedMotion(); const motionValue = useMotionValue(value); const [shown, setShown] = useState(value); useEffect(() => { if (reduced) { setShown(value); return; } const controls = animate(motionValue, value, { duration: .42, ease: "easeOut" }); return controls.stop; }, [value, reduced, motionValue]); useEffect(() => motionValue.on("change", (next) => setShown(Math.round(next * 10) / 10)), [motionValue]); return <>{shown}</>; }
function Delta({ value }: { value: number }) { return <span className={value > 0 ? "delta up" : value < 0 ? "delta down" : "delta flat"}>{value > 0 ? "↗" : value < 0 ? "↘" : "—"} {Math.abs(value)}%</span>; }
export default function MarginNotes({ contact, month }: { contact: Contact; month: number }) { const row = rowFor(contact, month); return <div className="signal-cards">{signals.map((signal) => { const value = row[signalField[signal.key]] as number; return <motion.article className="signal-card" key={signal.key} initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .24 }}><div className="signal-top"><span className="signal-icon" aria-hidden>{signal.icon}</span><Delta value={deltaFor(contact, signal.key, month)}/></div><p className="signal-value"><Count value={value}/><small>{signal.unit}</small></p><p className="signal-label">{signal.label}</p></motion.article>; })}</div>; }
